import { deepFreeze, semanticHash } from '../../../shared-piping-model/index.js';
import { asciiCompare, assertExactKeys } from '../../contracts.js';
import { LAFEA_STAGE_REGISTRY_DEPENDENCY_HASH } from '../../bucket-registry.js';
import { requireLafeaApplicationTemplate } from '../../template-registry.js';
import { requireT3AnalyticalParameterSchema } from '../../parameter-schemas/analytical.js';

export const LAFEA_TEMPLATE_COMPILER_BINDING_SCHEMA =
  'lafea-template-compiler-binding/v1';

const BINDING_KEYS = Object.freeze([
  'boundaryCompilerId',
  'compilerVersion',
  'entryStageId',
  'geometryCompilerId',
  'limitations',
  'loadCompilerId',
  'parameterSchemaId',
  'parentRegistryHash',
  'requiredEnginePackage',
  'requiredInputContractRole',
  'status',
  'templateId',
]);

export const LAFEA_T3_ANALYTICAL_COMPILER_BINDINGS = Object.freeze([
  binding({
    templateId: 'ALG-LOAD-REFERENCE-TRANSFER',
    geometryCompilerId: 'alg-load-reference-transfer-geometry/v1',
    loadCompilerId: 'alg-load-reference-transfer-loads/v1',
    boundaryCompilerId: 'analytical-no-boundary/v1',
    limitations: [
      'LAFEA.1 source compilation only; no engine execution.',
      'No pressure-baseline request is generated by this compiler binding.',
    ],
  }),
  binding({
    templateId: 'ALG-PIPE-SECTION-COMBINED',
    geometryCompilerId: 'alg-pipe-section-combined-geometry/v1',
    loadCompilerId: 'alg-pipe-section-combined-loads/v1',
    boundaryCompilerId: 'analytical-no-boundary/v1',
    limitations: [
      'Requires caller-supplied validated LAFEA.1 model and result evidence.',
      'LAFEA.2 request compilation only; no engine execution or stress calculation.',
    ],
  }),
].sort((left, right) => asciiCompare(left.templateId, right.templateId)));

export function requireT3AnalyticalCompilerBinding(templateId) {
  const result = LAFEA_T3_ANALYTICAL_COMPILER_BINDINGS
    .find((entry) => entry.templateId === templateId);
  if (!result) throw new TypeError(`Unsupported T3 analytical compiler binding: ${templateId}.`);
  return result;
}

export function validateT3AnalyticalCompilerBinding(value) {
  const errors = [];
  try {
    assertExactKeys(
      value,
      [...BINDING_KEYS, 'schema', 'semanticHash'],
      'Analytical compiler binding',
    );
    if (value.schema !== LAFEA_TEMPLATE_COMPILER_BINDING_SCHEMA) {
      throw new TypeError('Analytical compiler binding schema is invalid.');
    }
    const { schema: ignoredSchema, semanticHash: ignoredHash, ...input } = value;
    void ignoredSchema;
    void ignoredHash;
    const expected = binding(input);
    if (value.semanticHash !== expected.semanticHash) {
      throw new TypeError('Analytical compiler binding hash is invalid.');
    }
  } catch (error) {
    errors.push(error instanceof Error ? error.message : String(error));
  }
  return deepFreeze({ ok: errors.length === 0, errors });
}

function binding({
  templateId,
  geometryCompilerId,
  loadCompilerId,
  boundaryCompilerId,
  limitations,
  compilerVersion = '1',
  status = 'DRAFT',
  parameterSchemaId = null,
  entryStageId = null,
  requiredEnginePackage = null,
  requiredInputContractRole = null,
  parentRegistryHash = LAFEA_STAGE_REGISTRY_DEPENDENCY_HASH,
}) {
  const input = {
    templateId,
    parameterSchemaId,
    geometryCompilerId,
    loadCompilerId,
    boundaryCompilerId,
    compilerVersion,
    entryStageId,
    requiredEnginePackage,
    requiredInputContractRole,
    parentRegistryHash,
    status,
    limitations,
  };
  assertExactKeys(input, BINDING_KEYS, 'Analytical compiler binding input');
  const template = requireLafeaApplicationTemplate(templateId);
  const schema = requireT3AnalyticalParameterSchema(templateId);
  const base = {
    schema: LAFEA_TEMPLATE_COMPILER_BINDING_SCHEMA,
    templateId,
    parameterSchemaId: parameterSchemaId ?? schema.parameterSchemaId,
    geometryCompilerId: text(geometryCompilerId, 'geometryCompilerId'),
    loadCompilerId: text(loadCompilerId, 'loadCompilerId'),
    boundaryCompilerId: text(boundaryCompilerId, 'boundaryCompilerId'),
    compilerVersion: text(compilerVersion, 'compilerVersion'),
    entryStageId: entryStageId ?? template.entryStageId,
    requiredEnginePackage: requiredEnginePackage ?? template.requiredEnginePackage,
    requiredInputContractRole:
      requiredInputContractRole ?? template.requiredInputContractRole,
    parentRegistryHash,
    status,
    limitations: sortedStrings(limitations),
  };
  if (base.parameterSchemaId !== template.parameterSchemaId) {
    throw new TypeError('Compiler binding parameter schema does not match template authority.');
  }
  if (base.entryStageId !== template.entryStageId) {
    throw new TypeError('Compiler binding cannot override the template entry stage.');
  }
  if (base.requiredEnginePackage !== template.requiredEnginePackage) {
    throw new TypeError('Compiler binding cannot override the registered engine package.');
  }
  if (base.requiredInputContractRole !== template.requiredInputContractRole) {
    throw new TypeError('Compiler binding cannot override the registered input contract role.');
  }
  if (base.parentRegistryHash !== LAFEA_STAGE_REGISTRY_DEPENDENCY_HASH) {
    throw new TypeError('Compiler binding registry parent is stale.');
  }
  if (base.status !== 'DRAFT') {
    throw new TypeError('T3 compiler bindings must remain DRAFT.');
  }
  return deepFreeze({ ...base, semanticHash: semanticHash(base) });
}

function sortedStrings(values) {
  if (!Array.isArray(values) || values.some((value) => typeof value !== 'string' || !value)) {
    throw new TypeError('Compiler binding limitations must be non-empty strings.');
  }
  return [...new Set(values)].sort(asciiCompare);
}

function text(value, field) {
  if (typeof value !== 'string' || !value.trim()) {
    throw new TypeError(`${field} must be a non-empty string.`);
  }
  return value.trim();
}
