/** CAE-style presentation for the LFEA workbench. */
export function lfeaShellV2Styles() {
  return `
.lfea-workbench.lfea-shell-v2{display:flex;flex-direction:column;gap:0;min-height:100%;height:100%;max-width:none;margin:0;padding:0;background:var(--lfea-canvas);color:var(--lfea-text);overflow:hidden}
.lfea-shell-v2 button,.lfea-shell-v2 select,.lfea-shell-v2 input,.lfea-shell-v2 textarea{font:inherit}
.lfea-shell-v2 button,.lfea-shell-v2 select,.lfea-shell-v2 input{border:1px solid var(--lfea-border-strong);border-radius:5px;background:#0a1424;color:var(--lfea-text)}
.lfea-shell-v2 button{padding:6px 9px;cursor:pointer}.lfea-shell-v2 button:disabled{opacity:.45;cursor:not-allowed}
.lfea-shell-v2 textarea{box-sizing:border-box;width:100%;min-height:180px;padding:9px;border:1px solid var(--lfea-border-strong);border-radius:5px;background:#050b14;color:#dbeafe;font:12px/1.5 ui-monospace,monospace;resize:vertical}
.lfea-shell-v2__command-bar{display:grid;grid-template-columns:minmax(220px,auto) minmax(0,1fr) auto;gap:10px;align-items:center;min-height:46px;padding:7px 10px;border-bottom:1px solid var(--lfea-border);background:var(--lfea-panel-strong);flex:none}
.lfea-shell-v2__identity,.lfea-shell-v2__command-actions{display:flex;gap:7px;align-items:center;min-width:0;flex-wrap:wrap}
.lfea-shell-v2__identity-text{max-width:240px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:var(--lfea-muted);font-size:11px}
.lfea-shell-v2__file-button{display:inline-flex;align-items:center;padding:6px 9px;border:1px solid var(--lfea-border-strong);border-radius:5px;background:#0a1424;cursor:pointer}.lfea-shell-v2__file-button input{display:none}
.lfea-shell-v2__control-label{display:inline-flex;align-items:center;gap:5px;color:var(--lfea-muted);font-size:11px}.lfea-shell-v2__control-label select,.lfea-shell-v2__control-label input{padding:5px 7px}.lfea-shell-v2__control-label input{width:72px}
.lfea-shell-v2 .lfea-workbench__status{padding:4px 7px;border:1px solid var(--lfea-border-strong);border-radius:999px;font-size:11px;font-weight:800}.lfea-shell-v2 .lfea-workbench__status[data-status="QUALIFIED"]{color:#86efac;border-color:#15803d}.lfea-shell-v2 .lfea-workbench__status[data-status="FAILED"]{color:#fca5a5;border-color:#b91c1c}.lfea-shell-v2 .lfea-workbench__progress{color:var(--lfea-accent);font-size:11px}
.lfea-shell-v2__workbench{display:grid;grid-template-columns:220px minmax(420px,1fr) minmax(280px,360px);min-height:0;flex:1;overflow:hidden}
.lfea-shell-v2__navigator,.lfea-shell-v2__inspector{min-height:0;overflow:auto;background:var(--lfea-panel-strong)}.lfea-shell-v2__navigator{padding:10px;border-right:1px solid var(--lfea-border)}.lfea-shell-v2__inspector{padding:10px;border-left:1px solid var(--lfea-border)}
.lfea-shell-v2__navigator h2,.lfea-shell-v2__inspector h2{margin:0 0 9px;font-size:13px;text-transform:uppercase;letter-spacing:.08em;color:var(--lfea-accent)}
.lfea-shell-v2__navigator-list{display:grid;gap:4px}.lfea-shell-v2__navigator-list button{display:flex;justify-content:space-between;gap:8px;width:100%;text-align:left;border-color:transparent;background:transparent}.lfea-shell-v2__navigator-list button[aria-current="page"]{border-color:rgba(56,189,248,.45);background:rgba(56,189,248,.12);color:var(--lfea-accent)}
.lfea-shell-v2__count{color:var(--lfea-muted);font-size:10px}.lfea-shell-v2__navigator-summary,.lfea-shell-v2__blocked-capability{display:grid;gap:5px;margin-top:12px;padding:9px;border:1px solid var(--lfea-border);border-radius:6px;background:var(--lfea-panel)}.lfea-shell-v2__navigator-summary h3{margin:0 0 3px;font-size:11px;color:var(--lfea-muted)}
.lfea-shell-v2__blocked-capability{border-color:#7c2d12;background:#1b120b}.lfea-shell-v2__blocked-capability>span{color:#fdba74;font-weight:800}.lfea-shell-v2__blocked-capability code{overflow-wrap:anywhere;color:#fed7aa;font-size:10px}.lfea-shell-v2__blocked-capability p{margin:0;color:#cbd5e1;font-size:11px;line-height:1.35}
.lfea-shell-v2__fact{display:flex;justify-content:space-between;gap:10px;color:var(--lfea-muted);font-size:11px}.lfea-shell-v2__fact strong{color:var(--lfea-text)}
.lfea-shell-v2__viewport{display:flex;flex-direction:column;min-width:0;min-height:0;background:#050a12}.lfea-shell-v2__panel-heading{display:flex;justify-content:space-between;gap:12px;padding:7px 10px;border-bottom:1px solid var(--lfea-border);background:var(--lfea-panel);font-size:11px}.lfea-shell-v2__panel-heading>div{font-weight:800;color:var(--lfea-accent)}.lfea-shell-v2__panel-heading>span{color:var(--lfea-muted)}
.lfea-shell-v2__viewport-host{display:flex;align-items:center;justify-content:center;flex:1;min-height:240px;overflow:auto;border:0;background:#050a12}.lfea-shell-v2__viewport-host svg{width:100%;height:100%;max-height:100%}.lfea-shell-v2__viewport>.lfea-workbench__authority{margin:0;padding:6px 10px;border-top:1px solid var(--lfea-border);border-left:0;background:var(--lfea-panel);font-size:11px}.lfea-shell-v2__viewport>.lfea-workbench__node-draft{padding:7px 10px;border-top:1px solid var(--lfea-border);background:var(--lfea-panel-strong)}
.lfea-shell-v2__empty{padding:24px;color:var(--lfea-muted);text-align:center}
.lfea-shell-v2__record-inspector,.lfea-shell-v2__results{display:grid;gap:8px}.lfea-shell-v2__record-inspector>select{width:100%;padding:6px}.lfea-shell-v2__inspector .lfea-workbench__table{max-height:230px;overflow:auto}.lfea-shell-v2__inspector table{width:100%;border-collapse:collapse;font-size:11px}.lfea-shell-v2__inspector th,.lfea-shell-v2__inspector td{padding:5px;border:1px solid var(--lfea-border-strong);text-align:left;vertical-align:top;overflow-wrap:anywhere}.lfea-shell-v2__inspector tr[data-selected="true"]{outline:2px solid var(--lfea-accent-warm);outline-offset:-2px}
.lfea-shell-v2__result-summary{display:grid;gap:5px;padding:8px;border:1px solid var(--lfea-border);border-radius:6px;background:var(--lfea-panel)}.lfea-shell-v2__results h3{margin:8px 0 4px;font-size:11px;color:var(--lfea-accent-warm)}.lfea-shell-v2__results pre{max-height:220px;overflow:auto;font-size:10px}
.lfea-shell-v2__pipeline{display:grid;grid-template-columns:210px minmax(0,1fr);gap:10px;padding:7px 10px;border-top:1px solid var(--lfea-border);border-bottom:1px solid var(--lfea-border);background:var(--lfea-panel);flex:none}.lfea-shell-v2__pipeline-heading{display:grid;gap:2px}.lfea-shell-v2__pipeline-heading strong{font-size:11px;color:var(--lfea-accent)}.lfea-shell-v2__pipeline-heading span{color:var(--lfea-muted);font-size:9px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.lfea-shell-v2__pipeline-list{display:grid;grid-template-columns:repeat(7,minmax(76px,1fr));gap:4px;margin:0;padding:0;list-style:none}.lfea-shell-v2__pipeline-step{display:grid;grid-template-columns:auto 1fr;column-gap:5px;align-items:center;padding:5px 6px;border:1px solid var(--lfea-border);border-radius:5px;background:var(--lfea-panel-strong);font-size:9px}.lfea-shell-v2__pipeline-step strong{font-size:9px}.lfea-shell-v2__step-state{grid-column:2;color:var(--lfea-muted)}.lfea-shell-v2__pipeline-step[data-state="RUNNING"]{border-color:var(--lfea-accent)}.lfea-shell-v2__pipeline-step[data-state="WARNING"]{border-color:var(--lfea-warning)}.lfea-shell-v2__pipeline-step[data-state="BLOCKED"]{border-color:var(--lfea-error)}.lfea-shell-v2__pipeline-step[data-state="COMPLETE"] .lfea-shell-v2__step-symbol{color:var(--lfea-success)}
.lfea-shell-v2__diagnostics,.lfea-shell-v2__verification,.lfea-shell-v2__source-drawer{border-bottom:1px solid var(--lfea-border);background:var(--lfea-panel-strong);flex:none}.lfea-shell-v2__diagnostics summary,.lfea-shell-v2__verification summary,.lfea-shell-v2__source-drawer summary{display:flex;gap:10px;align-items:center;padding:7px 10px;cursor:pointer;font-size:11px}.lfea-shell-v2__diagnostics summary span{color:var(--lfea-muted)}
.lfea-shell-v2__diagnostic-list,.lfea-shell-v2__source-body{display:grid;gap:7px;max-height:240px;overflow:auto;padding:8px 10px;background:var(--lfea-canvas)}.lfea-shell-v2__diagnostic{padding:7px;border:1px solid var(--lfea-border);border-radius:5px;background:var(--lfea-panel)}.lfea-shell-v2__diagnostic header{display:flex;gap:8px;align-items:center}.lfea-shell-v2__diagnostic p{margin:5px 0}.lfea-shell-v2__diagnostic[data-severity="ERROR"]{border-color:#7f1d1d}.lfea-shell-v2__diagnostic[data-severity="WARNING"]{border-color:#78350f}.lfea-shell-v2__severity{font-size:9px;font-weight:800;color:var(--lfea-muted)}
.lfea-shell-v2__verification-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;max-height:320px;overflow:auto;padding:9px;background:var(--lfea-canvas)}.lfea-shell-v2__verification-grid section{min-width:0;padding:8px;border:1px solid var(--lfea-border);border-radius:6px;background:var(--lfea-panel)}.lfea-shell-v2__verification-grid h3{margin:0 0 7px;font-size:11px;color:var(--lfea-accent)}
.lfea-shell-v2__source-body textarea{min-height:220px}.lfea-shell-v2__muted{margin:0;color:var(--lfea-muted);font-size:11px}.lfea-shell-v2__contract-only{position:absolute!important;width:1px!important;height:1px!important;overflow:hidden!important;clip:rect(0 0 0 0)!important;white-space:nowrap!important}
@media(max-width:1100px){.lfea-shell-v2__workbench{grid-template-columns:180px minmax(380px,1fr)}.lfea-shell-v2__inspector{grid-column:1/-1;max-height:300px;border-left:0;border-top:1px solid var(--lfea-border)}.lfea-shell-v2__command-bar{grid-template-columns:1fr}.lfea-shell-v2__pipeline{grid-template-columns:1fr}.lfea-shell-v2__pipeline-list{overflow-x:auto}}
@media(max-width:720px){.lfea-shell-v2{height:auto;overflow:visible}.lfea-shell-v2__workbench{display:block;overflow:visible}.lfea-shell-v2__navigator,.lfea-shell-v2__inspector{max-height:none;border:0;border-bottom:1px solid var(--lfea-border)}.lfea-shell-v2__viewport{min-height:420px}.lfea-shell-v2__pipeline-list{grid-template-columns:repeat(7,110px)}.lfea-shell-v2__verification-grid{grid-template-columns:1fr}}
`;
}

export const LFEA_SHELL_V2_STYLES = lfeaShellV2Styles();
