import { chmod,mkdir,readFile,writeFile } from 'node:fs/promises';import { spawn } from 'node:child_process';import { resolve } from 'node:path';import { E,NU,TABLE,SOLVER_HASH } from './config.mjs';import { hash } from './evidence.mjs';
const nodes=`*NODE\n1,0,0,0\n2,1,0,0\n3,1,1,0\n4,0,1,0\n5,0,0,1\n6,1,0,1\n7,1,1,1\n8,0,1,1\n*ELEMENT,TYPE=C3D8,ELSET=EALL\n1,1,2,3,4,5,6,7,8\n`;
const sets=`*NSET,NSET=X0\n1,4,5,8\n*NSET,NSET=X1\n2,3,6,7\n*NSET,NSET=Y0\n1,2,5,6\n*NSET,NSET=Y1\n3,4,7,8\n*NSET,NSET=Z0\n1,2,3,4\n*NSET,NSET=Z1\n5,6,7,8\n*NSET,NSET=ALL\n1,2,3,4,5,6,7,8\n`;
export function baseDeck(){return `*HEADING\nNC04 exact material specimen\n${nodes}*MATERIAL,NAME=MAT\n*ELASTIC\n${E},${NU}\n*PLASTIC\n${TABLE.map(r=>r.join(',')).join('\n')}\n*SOLID SECTION,ELSET=EALL,MATERIAL=MAT\n${sets}`;}
export function step(boundary,initial=.1){return `*STEP,NLGEOM=NO,INC=300\n*STATIC\n${initial},1.0,1e-6,${initial}\n*BOUNDARY,OP=NEW\n${boundary}\n*EL PRINT,ELSET=EALL,FREQUENCY=1\nS,E,PEEQ\n*END STEP\n`;}
export const support=`X0,1,1,0.\nY0,2,2,0.\nZ0,3,3,0.`;
export async function runCase({name,deck,solver,outDir}){const dir=resolve(outDir,name);await mkdir(dir,{recursive:true});await chmod(solver,0o755);const inp=resolve(dir,`${name}.inp`);await writeFile(inp,deck);await new Promise((ok,bad)=>{const p=spawn(solver,['-i',name],{cwd:dir,stdio:['ignore','pipe','pipe']});let log='';p.stdout.on('data',d=>log+=d);p.stderr.on('data',d=>log+=d);p.on('close',async c=>{await writeFile(resolve(dir,'solver.log'),log);c===0?ok():bad(Error(`${name} solver exit ${c}`));});});const dat=await readFile(resolve(dir,`${name}.dat`));const cvg=await readFile(resolve(dir,`${name}.cvg`));return {name,deckHash:hash(deck),rawOutputHash:hash(Buffer.concat([dat,cvg])),solverHash:SOLVER_HASH,...parseDat(dat.toString())};}
function parseDat(t){const grab=(label,n)=>{const re=new RegExp(` ${label} .*? time\\s+([0-9.E+-]+)\\n\\n((?:\\s+\\d+\\s+\\d+.*\\n)+)`,'gi');let m,last;while((m=re.exec(t))){const rows=m[2].trim().split(/\n/u).map(l=>l.trim().split(/\s+/u).slice(2,2+n).map(Number));last={time:Number(m[1]),values:Array.from({length:n},(_,i)=>rows.reduce((a,r)=>a+r[i],0)/rows.length)};}if(!last)throw Error(`missing ${label}`);return last;};const stress=grab('stresses',6),strain=grab('strains',6);const re=/equivalent plastic strain .*? time\s+([0-9.E+-]+)\n\n((?:\s+\d+\s+\d+.*\n)+)/giu;let m,peeq=0;while((m=re.exec(t))){const a=m[2].trim().split(/\n/u).map(l=>Number(l.trim().split(/\s+/u)[2]));peeq=a.reduce((x,y)=>x+y,0)/a.length;}return {stress:stress.values,strain:strain.values,peeq};}
export function yieldAt(ep){for(let i=1;i<TABLE.length;i++){if(ep<=TABLE[i][1]){const [s0,e0]=TABLE[i-1],[s1,e1]=TABLE[i];return s0+(s1-s0)*(ep-e0)/(e1-e0);}}const [s0,e0]=TABLE.at(-2),[s1,e1]=TABLE.at(-1);return s0+(s1-s0)*(ep-e0)/(e1-e0);}
export function mises(s){const [a,b,c,d,e,f]=s;return Math.sqrt(.5*((a-b)**2+(b-c)**2+(c-a)**2)+3*(d*d+e*e+f*f));}
