import { deepFreeze } from '../../shared-piping-model/index.js';
import { createTemplateParameterSchema, asciiCompare } from '../contracts.js';
import { requireLafeaApplicationTemplate } from '../template-registry.js';

export const LAFEA_T3_ANALYTICAL_PARAMETER_SCHEMAS = Object.freeze([
  loadReferenceTransferSchema(),
  pipeSectionCombinedSchema(),
].sort((left, right) => asciiCompare(left.templateId, right.templateId)));

export const LAFEA_T3_ANALYTICAL_PARAMETER_SCHEMA_IDS = Object.freeze(
  LAFEA_T3_ANALYTICAL_PARAMETER_SCHEMAS.map((schema) => schema.parameterSchemaId),
);

export function requireT3AnalyticalParameterSchema(templateId) {
  const schema = LAFEA_T3_ANALYTICAL_PARAMETER_SCHEMAS
    .find((item) => item.templateId === templateId);
  if (!schema) {
    throw new TypeError(`Unsupported T3 analytical template parameter schema: ${templateId}.`);
  }
  return schema;
}

function loadReferenceTransferSchema() {
  const template = requireLafeaApplicationTemplate('ALG-LOAD-REFERENCE-TRANSFER');
  return createTemplateParameterSchema({
    parameterSchemaId: template.parameterSchemaId,
    templateId: template.templateId,
    parameters: [
      recordParameter('identity', 'Model and source identity'),
      recordParameter('units', 'Declared engineering units'),
      recordParameter('pipeContext', 'Pipe geometry, basis and source context'),
      recordParameter('loadTransfer', 'Reference points and physical resultant cases'),
      recordParameter('qualificationProfile', 'Registered LAFEA.1 qualification profile'),
      recordParameter('limitations', 'Caller-declared additional limitations', false),
    ],
    limitations: [
      'The compiler emits a LAFEA.1 load-transfer source only.',
      'Pressure definitions and pressure-result requests are not generated by this template.',
      'No footprint stiffness, local attachment stress, utilization or code result is calculated.',
    ],
  });
}

function pipeSectionCombinedSchema() {
  const template = requireLafeaApplicationTemplate('ALG-PIPE-SECTION-COMBINED');
  return createTemplateParameterSchema({
    parameterSchemaId: template.parameterSchemaId,
    templateId: template.templateId,
    parameters: [
      textParameter('requestIdentity', 'Screening request identity'),
      textParameter('requestVersion', 'Screening request version'),
      recordParameter('sourceEvidence', 'Validated LAFEA.1 model and result evidence'),
      recordParameter('screeningCases', 'Mechanical and pressure case combinations'),
      recordParameter('evaluationLocations', 'Pipe-wall evaluation locations'),
      recordParameter('envelopeQuantities', 'Requested screening envelope quantities'),
      recordParameter('qualificationProfile', 'Registered LAFEA.2 qualification profile'),
      recordParameter('limitations', 'Caller-declared additional limitations', false),
    ],
    limitations: [
      'The compiler requires pre-existing LAFEA.1 source and result evidence.',
      'The compiler does not execute LAFEA.1 or LAFEA.2.',
      'Outputs remain nominal pipe-section screening inputs and are not local discontinuity stress or code assessment.',
    ],
  });
}

function recordParameter(parameterId, label, sourceRequired = true) {
  return descriptor({
    parameterId,
    label,
    valueKind: 'JSON_RECORD',
    sourceRequired,
  });
}

function textParameter(parameterId, label) {
  return descriptor({
    parameterId,
    label,
    valueKind: 'TEXT',
    sourceRequired: true,
  });
}

function descriptor({
  parameterId,
  label,
  valueKind,
  sourceRequired,
}) {
  return deepFreeze({
    parameterId,
    label,
    valueKind,
    required: true,
    nullable: false,
    canonicalUnit: null,
    allowedUnits: [],
    minimum: null,
    maximum: null,
    enumValues: [],
    sourceRequired,
    dependencies: [],
  });
}
