export {
  CANONICAL_ID_ORDER_ID,
  CANONICAL_NODE_ID_GRAMMAR_ID,
  CANONICAL_ORDERING_CONVENTION_SCHEMA,
  compareCanonicalIds,
  requireCanonicalNodeId,
} from './identifiers.js';

export {
  LINEAR_FEA_UNITS,
  LINEAR_FEA_UNITS_SCHEMA,
  requireLinearFeaUnits,
} from './units.js';

export {
  DOF_ORDER,
  ELEMENT_DOF_ORDER,
  ELEMENT_END_ACTION_CONVENTION_ID,
  ELEMENT_END_ORDER,
  ELEMENT_MATRIX_STORAGE_ID,
  ELEMENT_VECTOR_LAYOUT_ID,
  ELEMENT_VECTOR_LAYOUT_SCHEMA,
  END_ACTION_CONVENTION,
  END_ACTION_CONVENTION_SCHEMA,
  LINEAR_FEA_CONVENTIONS,
  LINEAR_FEA_CONVENTIONS_SCHEMA,
  LOCAL_RESULT_ORDER,
  NUMERIC_NORMALIZATION_CONVENTION_SCHEMA,
  NUMERIC_NORMALIZATION_ID,
  PRESCRIBED_DISPLACEMENT_CONVENTION_ID,
  REACTION_CONVENTION_ID,
  THERMAL_STRAIN_CONVENTION_ID,
  TRANSFORMATION_CONVENTION_ID,
  TRANSFORMATION_CONVENTION_SCHEMA,
  VECTOR_ORIENTATION_ID,
  dofIndex,
  elementDofIndex,
  elementMatrixIndex,
  endIndex,
  globalDofIdentity,
  normalizeLinearFeaNumber,
  requireLinearFeaConventions,
} from './conventions.js';
