export const EMPIRICAL_FAILURE_CODES = Object.freeze({
  INPUT_INCOMPLETE: 'INPUT_INCOMPLETE',
  GEOMETRY_INVALID: 'GEOMETRY_INVALID',
  SECTION_INVALID: 'SECTION_INVALID',
  MASS_SOURCE_UNRESOLVED: 'MASS_SOURCE_UNRESOLVED',
  SUPPORT_CAPABILITY_UNKNOWN: 'SUPPORT_CAPABILITY_UNKNOWN',
  CODE_DATASET_UNRESOLVED: 'CODE_DATASET_UNRESOLVED',
  SOURCE_CITATION_UNRESOLVED: 'SOURCE_CITATION_UNRESOLVED',
  MATRIX_SINGULAR: 'MATRIX_SINGULAR',
  SYSTEM_ILL_CONDITIONED: 'SYSTEM_ILL_CONDITIONED',
  CONTACT_NONCONVERGENT: 'CONTACT_NONCONVERGENT',
  CONTACT_ACTIVE_SET_OSCILLATION: 'CONTACT_ACTIVE_SET_OSCILLATION',
  CONTACT_RECONTACT_RULE_UNQUALIFIED: 'CONTACT_RECONTACT_RULE_UNQUALIFIED',
  BEND_CONVERGENCE_FAILED: 'BEND_CONVERGENCE_FAILED',
  OUTSIDE_QUALIFIED_SCOPE: 'OUTSIDE_QUALIFIED_SCOPE',
  BENCHMARK_NOT_QUALIFIED: 'BENCHMARK_NOT_QUALIFIED',
  TOPOLOGY_LOOP_PROFILE_REQUIRED: 'TOPOLOGY_LOOP_PROFILE_REQUIRED',
  TOPOLOGY_BRANCH_PROFILE_REQUIRED: 'TOPOLOGY_BRANCH_PROFILE_REQUIRED',
  BOUNDARY_CONDITION_UNRESOLVED: 'BOUNDARY_CONDITION_UNRESOLVED',
  RESTRAINT_AXIS_AMBIGUOUS: 'RESTRAINT_AXIS_AMBIGUOUS',
  EMPIRICAL_PROFILE_UNQUALIFIED: 'EMPIRICAL_PROFILE_UNQUALIFIED',
  COUPLED_STIFFNESS_RANK_DEFICIENT: 'COUPLED_STIFFNESS_RANK_DEFICIENT',
  LOAD_CASE_OWNERSHIP_MISMATCH: 'LOAD_CASE_OWNERSHIP_MISMATCH',
});

export class EmpiricalPipingError extends Error {
  constructor(code, message, evidence = {}) {
    super(message);
    this.name = 'EmpiricalPipingError';
    this.code = code;
    this.evidence = Object.freeze({ ...evidence });
  }
}

export function empiricalFailure(code, message, evidence = {}) {
  return new EmpiricalPipingError(code, message, evidence);
}
